[tool.poetry]
name = "class2ics"
version = "0.1.0"
description = ""
authors = ["b3nguang <1127786222@qq.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
tzlocal = "^5.2"
ical = "^8.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
